version: '3.5'

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net

  app:
    build:
      context: ./cmd
      args:
        apiPort: ${API_PORT}
    volumes:
      - ./cmd:/app
    networks:
      - net
    depends_on:
      - postgres

networks:
  net:
    driver: bridge
    external: false