PUT http://localhost:3000/todo/add
Content-Type: application/json

{
  "text": "test_text"
}

###

POST http://localhost:3000/todo/complete/1

###

GET http://localhost:3000/todo/uncompleted

###

GET http://localhost:3000/todo/completed

###

DELETE http://localhost:3000/todo/delete/1