PUT http://localhost:3000/task
Content-Type: application/json

{
  "text": "test_text"
}

###
GET http://localhost:3000/task/1

###
POST http://localhost:3000/task/1

###
DELETE http://localhost:3000/task/1

###
GET http://localhost:3000/task/uncompleted

###
GET http://localhost:3000/task/completed